### ISSUE TITLE
Colaboration

### ISSUE THREAD

**Issue by Zriel88** [will-hart/AnvilEditor#37]
I write this issue into Github to allow easier comunication.
Right now I'm interested in improving and moving forward this project. Our community has a low share of editors and using and teaching to make missions using this framework would increase that share (and probably will help other comunities too).
Though not perfect, the framework does a lot of things in a way that I like a lot.

Though, there's a big issue with me. i'm not a Developer, just a Systems operator with knowledge in scripting, and C# is far more advanced than a scripting language. 

Bit by bit a try to understand the code, and understand the language in order to make things how I want them, but I'm far from getting a single line of usable code.

I would like to share some ideas though, and I'm far more experienced with the SQF code, and myself have developed some scripts and modifications to existing scripts (My EOS script works with HC out of the box and is able to let editor decide on which direction units spawn in Bastion mode, and as well to not control skill of units (if using mods like ASR AI or bCombat).

I have also done some digging about the issues with maps, size and zooming, and seems that image pyramids would be the best approach (as always, being a noob in C# and developing in general, I just throw ideas in case you haven't already thought of them).

Last, I would like to thank you for your work.
Cheers!

**Comment by will-hart** [comment]
Hello Zriel, I'm glad you're finding Anvil useful and have come over to github for a chat :) I'd welcome any collaboration on Anvil although I don't really have the time at the moment to develop features "on request". If you have any SQF suggestions or so on we can talk about them in here and see where that leads.
