### ISSUE TITLE
The tag 'MultiLineTextEditor' does not exist

### ISSUE THREAD

**Issue by c9jester** [will-hart/AnvilEditor#38]
I'm encountering this error when trying to build the master branch in Visual Studio.

Warning	1	Could not resolve this reference. Could not locate the assembly "Xceed.Wpf.Toolkit". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

Error	2	The tag 'MultiLineTextEditor' does not exist in XML namespace 'http://schemas.xceed.com/wpf/xaml/toolkit'. Line 135 Position 22.	C:\Users\Jester\Documents\AnvilEditor\AnvilEditor\MainWindow.xaml

Warning	3	The referenced component 'Xceed.Wpf.Toolkit' could not be found.

**Comment by c9jester** [comment]
I figured out that I needed to install the Extended WPF Toolkit through the Nuget Package Manager. For future reference for others: https://www.nuget.org/packages/Extended.Wpf.Toolkit/

**Comment by will-hart** [comment]
Thanks for the issue report. The latest develop version fixes the dependencies here.
